[package]
name = "retypd-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
nom = "7"
petgraph = "0.6.5"
env_logger = "0.11.3"
log = "0.4.21"
clap = { version = "4.5.4", features = ["cargo"] }
